name: smython
description: A subset of Python 3, just large enough to run `fac`.
version: 0.1.0
author: Stefan Matthias Aust <eibaan@gmail.com>
homepage: https://github.com/sma/smythondart/
environment:
  sdk: '>=2.2.0 <3.0.0'